# 特征选择

In [1]:
import numpy as np
import warnings

from sklearn.feature_selection import VarianceThreshold,SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression

In [2]:
X = np.array([
    [0, 2, 0, 3],
    [0, 1, 4, 3],
    [0.1, 1, 1, 3],
    [1, 2, 3, 1],
    [2, 3, 4, 3]
], dtype=np.float32)
Y = np.array([1,2,1,2,1])

## 方差选择法

In [3]:
# 基于方差选择最优的特征属性
variance = VarianceThreshold(threshold=0.7)
print(variance)
variance.fit(X)
print("各个特征属性的方差为:")
print(variance.variances_)
print('-----------------')
print(variance.transform(X))

VarianceThreshold(threshold=0.7)
各个特征属性的方差为:
[0.6176 0.56   2.64   0.64  ]
-----------------
[[0.]
 [4.]
 [1.]
 [3.]
 [4.]]


## 相关系数法

In [4]:
sk1 = SelectKBest(f_regression, k=2)
sk1.fit(X,Y)
print(sk1)
print('------------')
print(sk1.scores_)
print('------------')
print(sk1.transform(X))

SelectKBest(k=2, score_func=<function f_regression at 0x000001B751A8CA68>)
------------
[0.04736842 0.36       1.32       1.8       ]
------------
[[0. 3.]
 [4. 3.]
 [1. 3.]
 [3. 1.]
 [4. 3.]]


## 卡方检验

In [5]:
# 使用chi2的时候要求特征属性的取值为非负数
sk2 = SelectKBest(chi2, k=2)
sk2.fit(X, Y)
print(sk2)
print(sk2.scores_)
print(sk2.transform(X))

SelectKBest(k=2, score_func=<function chi2 at 0x000001B751A8C948>)
[0.07741936 0.16666667 1.68055556 0.46153846]
[[0. 3.]
 [4. 3.]
 [1. 3.]
 [3. 1.]
 [4. 3.]]


## Wrapper-递归特征消除法

In [6]:
# 基于特征消去法做的特征选择
estimator = LogisticRegression()
selector = RFE(estimator,step=2,n_features_to_select=3)
selector = selector.fit(X, Y)
print(selector.support_)
print(selector.n_features_)
print(selector.ranking_)
print(selector.transform(X))

[False  True  True  True]
3
[2 1 1 1]
[[2. 0. 3.]
 [1. 4. 3.]
 [1. 1. 3.]
 [2. 3. 1.]
 [3. 4. 3.]]


## Embedded【嵌入法】-基于惩罚项的特征选择法

In [7]:
X2 = np.array([
    [ 5.1,  3.5,  1.4,  0.2],
    [ 4.9,  3. ,  1.4,  0.2],
    [ -6.2,  0.4,  5.4,  2.3],
    [ -5.9,  0. ,  5.1,  1.8]
], dtype=np.float64)
Y2 = np.array([0, 0, 2, 2])
estimator = LogisticRegression(penalty='l2', C=0.1)
sfm = SelectFromModel(estimator,threshold=0.09)
sfm.fit(X2, Y2)
print(sfm.transform(X2))
print("系数:")
print(sfm.estimator_.coef_)

[[ 5.1  1.4]
 [ 4.9  1.4]
 [-6.2  5.4]
 [-5.9  5.1]]
系数:
[[-0.28319012 -0.07821437  0.09858841  0.04716025]]
