# kmeans

In [1]:
import numpy as np
import sys

X = np.array([[1.0, 2.0], [2.0, 2.0], [6.0, 8.0], [7.0, 8.0]])
C = np.array([[1.0, 2.0], [2.0, 2.0]])
# C = np.array([[2.0, 2.0], [1.0, 2.0]])
iters = 5  ###迭代次数
while iters > 0:
    ###计算每个样本到每个聚类中心的距离
    A = []
    for c in C:  ##聚类中心
        # print(c)
        # print(X-c)
        # print(np.sum((X-c)**2,axis=1))
        a = np.sqrt(np.sum((X - c) ** 2, axis=1))
        # print(a)
        A.append(a)
        # print(A)
        # sys.exit()
    A = np.array(A)
    print(A)
    print('---------------------------------')
    ###将样本分配的所属的聚类中心（获取最小值的下标）
    minidx = np.argmin(A, axis=0)
    print(minidx)
    print('---------------------------------')

    ###获取每个簇的样本
    for i in range(len(C)):
        a = X[minidx == i]  ###每个簇的样本
        print('a\n', a)
        C[i] = np.mean(a, axis=0)  ###更新我们的聚类中心
        # print(C[i])
    print('---------------------------------')
    print("C\n", C)
    # todo: 就是C不再更新停止
    print('---------------------------------')
    iters -= 1

# todo：封装成类【伪代码】，加上就是C不再更新停止

[[0.         1.         7.81024968 8.48528137]
 [1.         0.         7.21110255 7.81024968]]
---------------------------------
[0 1 1 1]
---------------------------------
a
 [[1. 2.]]
a
 [[2. 2.]
 [6. 8.]
 [7. 8.]]
---------------------------------
C
 [[1. 2.]
 [5. 6.]]
---------------------------------
[[0.         1.         7.81024968 8.48528137]
 [5.65685425 5.         2.23606798 2.82842712]]
---------------------------------
[0 0 1 1]
---------------------------------
a
 [[1. 2.]
 [2. 2.]]
a
 [[6. 8.]
 [7. 8.]]
---------------------------------
C
 [[1.5 2. ]
 [6.5 8. ]]
---------------------------------
[[0.5       0.5       7.5       8.1394103]
 [8.1394103 7.5       0.5       0.5      ]]
---------------------------------
[0 0 1 1]
---------------------------------
a
 [[1. 2.]
 [2. 2.]]
a
 [[6. 8.]
 [7. 8.]]
---------------------------------
C
 [[1.5 2. ]
 [6.5 8. ]]
---------------------------------
[[0.5       0.5       7.5       8.1394103]
 [8.1394103 7.5       0.5       0.5 

C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
