In [8]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

# bagging 回归

In [9]:
###数据
df = pd.DataFrame([[1, 10.56],
                   [2, 27],
                   [3, 39.1],
                   [4, 40.4],
                   [5, 58],
                   [6, 60.5],
                   [7, 79],
                   [8, 87],
                   [9, 90],
                   [10, 95]],
                  columns=['X', 'Y'])
print(df)

    X      Y
0   1  10.56
1   2  27.00
2   3  39.10
3   4  40.40
4   5  58.00
5   6  60.50
6   7  79.00
7   8  87.00
8   9  90.00
9  10  95.00


In [10]:
###做预测
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [18]:
M = []  ###用来存储弱学习器
n_trees = 200  ###构造的弱学习器的数量

for i in range(n_trees):  ##循环训练我们的弱学习器
    ###对样本进行有放回的抽样m次
    '''
    sample() 抽样
    n=None,  抽样数据的条数
    frac=None, 抽样的比例
    replace=False, 是否有放回抽样
    weights=None, 权重
    random_state=None, 随机数种子
    axis=None 维度
    '''
    tmp = df.sample(frac=1.0, replace=True)  ###不需要设置随机数种子
#     tmp = tmp.drop_duplicates()  # ##去重
    X = tmp.iloc[:, :-1]
    Y = tmp.iloc[:, -1]
    model = DecisionTreeRegressor(max_depth=1)
    model.fit(X, Y)

    M.append(model)

In [19]:
res = np.zeros(df.shape[0])
for j in M:
    res += j.predict(x)
y_hat = res / n_trees
print(y_hat)

[33.71699163 33.71699163 33.71699163 39.74694782 54.53475627 63.50074317
 74.87978627 81.81593869 82.04296726 82.04296726]


In [20]:
print('R2:', r2_score(y, y_hat))

R2: 0.8799770816184327


In [21]:
# 查看一下单棵树的效果
mode01 = DecisionTreeRegressor(max_depth=1)
mode01.fit(x, y)
y_hat_01 = mode01.predict(x)
print(y_hat_01)
print(mode01.score(x, y))

[29.265 29.265 29.265 29.265 78.25  78.25  78.25  78.25  78.25  78.25 ]
0.7622123252516444


# bagging分类

In [22]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score, accuracy_score

In [23]:
df = pd.DataFrame([[0, 1],
                   [1, 1],
                   [2, 1],
                   [3, -1],
                   [4, -1],
                   [5, -1],
                   [6, 1],
                   [7, 1],
                   [8, 1],
                   [9, -1]])

In [25]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [24]:
n_tree = 19
models = []

for i in range(n_tree):
    df2 = df.sample(frac=1.0, replace=True)
    # tmp = df2.drop_duplicates()  # ##去重
    X = df2.iloc[:, :-1]
    Y = df2.iloc[:, -1]
    dec = DecisionTreeClassifier(max_depth=1,splitter="random",max_features=1)
    dec.fit(X, Y)
    models.append(dec)

In [26]:
total = np.zeros(df.shape[0])
for i in range(n_tree):
    total += np.array(models[i].predict(x))
print(total)
y_hat = np.sign(total)
print(y_hat)
print(accuracy_score(y, y_hat))
print(f1_score(y, y_hat))

[11. 11.  9.  5.  3.  3.  5.  7.  3. -1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]
0.7
0.8


In [27]:
model01 = DecisionTreeClassifier(max_depth=1)
model01.fit(x, y)
y_hat_01 = model01.predict(x)
print(y_hat_01)
print(accuracy_score(y, y_hat_01))
print(f1_score(y, y_hat_01))

[ 1  1  1 -1 -1 -1 -1 -1 -1 -1]
0.7
0.6666666666666666
